(() => {
  'use strict';
  const FIRESTORE='https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
  const APP='https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
  let fs=null, db=null, roomId=null, unsubRoom=null, unsubPlayers=null, room=null, players=[];
  let canvas,ctx,balls=[],raf=0,last=0,aiming=false,drag={x:0,y:0},shotLock=false,solo=false;
  const W=1100,H=600,R=13,FRICTION=.985,CUSHION=.78,BALL_RESTITUTION=.93,MAX_SPEED=14;
  const pockets=[[24,24],[W/2,24],[W-24,24],[24,H-24],[W/2,H-24],[W-24,H-24]];
  const palette=['#f7c945','#3c72d8','#d946ef','#e64a35','#3ecb7a','#8b5cf6','#f97316','#111827','#ef4444','#22c55e','#06b6d4','#f59e0b','#2563eb','#ec4899','#14b8a6'];
  const $=s=>document.querySelector(s), uid=()=>window.YappathonVoiceContext?.currentUser?.uid||'guest-'+Math.random().toString(36).slice(2,8), name=()=>window.YappathonVoiceContext?.profile?.username||window.YappathonVoiceContext?.currentUser?.displayName||'Player';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function inject(){
    if($('#yc-pool-root')) return;
    const style=document.createElement('style'); style.id='yc-pool-style'; style.textContent=`
      #yc-pool-root{position:fixed;inset:0;z-index:99999;display:none;background:rgba(3,8,12,.78);backdrop-filter:blur(10px);align-items:center;justify-content:center;padding:22px;font-family:Inter,system-ui,sans-serif;color:#eef7f1}
      #yc-pool-root.open{display:flex} .yc-pool-card{width:min(1180px,96vw);max-height:94vh;overflow:auto;background:linear-gradient(145deg,#152c24,#0c1d17);border:1px solid #315a48;border-radius:26px;box-shadow:0 30px 100px #0009;padding:24px}
      .yc-pool-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}.yc-pool-title{font-size:25px;font-weight:800}.yc-pool-sub{color:#94b5a5;margin-left:8px;font-weight:600}.yc-pool-close{border:0;background:#ffffff12;color:#cfe5da;border-radius:12px;padding:9px 13px;font-size:20px}
      .yc-pool-lobby{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.yc-pool-panel{background:#07150f99;border:1px solid #29493c;border-radius:18px;padding:18px}.yc-pool-panel h3{margin:0 0 12px}.yc-pool-players{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.yc-pool-player{padding:13px;border-radius:14px;background:#ffffff08;border:1px solid #ffffff10;display:flex;align-items:center;gap:10px}.yc-pool-dot{width:12px;height:12px;border-radius:50%;background:#36d889;box-shadow:0 0 12px #36d88966}.yc-pool-wait{color:#789487}.yc-pool-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.yc-pool-btn{border:0;border-radius:12px;padding:12px 17px;font-weight:800;background:#8be0ad;color:#082016}.yc-pool-btn.secondary{background:#ffffff10;color:#d6eee2;border:1px solid #ffffff15}.yc-pool-code{font-family:monospace;font-size:20px;letter-spacing:.18em;background:#0003;border-radius:10px;padding:10px 12px;margin:8px 0 14px}.yc-pool-status{color:#9bbbad;min-height:24px}.yc-pool-game{display:none}.yc-pool-game.active{display:block}.yc-pool-board-wrap{background:#07120e;padding:16px;border-radius:20px;border:1px solid #29493c}.yc-pool-board{width:100%;display:block;border-radius:14px;box-shadow:inset 0 0 0 12px #5a351d,0 15px 45px #0008;background:#0b5734}.yc-pool-turn{margin:12px 0;color:#b7d9c9;font-weight:700}.yc-pool-turn strong{color:#fff}.yc-pool-names{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.yc-pool-name{padding:7px 11px;border-radius:999px;background:#ffffff09;border:1px solid #ffffff12}.yc-pool-name.active{background:#8be0ad22;border-color:#8be0ad;color:#b8f4d0}.yc-pool-help{color:#86a89a;text-align:center;margin-top:10px}.yc-pool-top-actions{display:flex;gap:8px}.yc-pool-error{color:#ff9a9a;margin-top:8px}
      @media(max-width:800px){.yc-pool-lobby{grid-template-columns:1fr}.yc-pool-players{grid-template-columns:1fr}.yc-pool-card{padding:14px}}
    `; document.head.appendChild(style);
    const root=document.createElement('div'); root.id='yc-pool-root'; root.innerHTML=`<div class="yc-pool-card">
      <div class="yc-pool-head"><div><span class="yc-pool-title">🎱 Pool</span><span class="yc-pool-sub">2–4 players</span></div><div class="yc-pool-top-actions"><button class="yc-pool-close" id="ycPoolClose">×</button></div></div>
      <section id="ycPoolLobby" class="yc-pool-lobby"><div class="yc-pool-panel"><h3>Pool lobby</h3><div class="yc-pool-status" id="ycPoolStatus">Create a room or join one.</div><div class="yc-pool-actions"><button class="yc-pool-btn" id="ycPoolCreate">Create room</button><button class="yc-pool-btn secondary" id="ycPoolJoin">Join room</button><button class="yc-pool-btn secondary" id="ycPoolSolo">Start solo</button></div><div class="yc-pool-error" id="ycPoolError"></div></div><div class="yc-pool-panel"><h3 id="ycPoolRoomTitle">Players</h3><div id="ycPoolPlayers" class="yc-pool-players"></div><div id="ycPoolCode" class="yc-pool-code" style="display:none"></div><div class="yc-pool-actions"><button class="yc-pool-btn" id="ycPoolStart" style="display:none">Start game</button><button class="yc-pool-btn secondary" id="ycPoolLeave" style="display:none">Leave room</button></div></div></section>
      <section id="ycPoolGame" class="yc-pool-game"><div class="yc-pool-names" id="ycPoolNames"></div><div class="yc-pool-turn" id="ycPoolTurn"></div><div class="yc-pool-board-wrap"><canvas class="yc-pool-board" id="ycPoolCanvas" width="1100" height="600"></canvas></div><div class="yc-pool-help">Drag back from the cue ball, aim, then release. Physics are simulated locally and the resulting table state is synchronized.</div><div class="yc-pool-actions"><button class="yc-pool-btn secondary" id="ycPoolGameLeave">Leave game</button></div></section>
    </div>`; document.body.appendChild(root);
    $('#ycPoolClose').onclick=close; $('#ycPoolCreate').onclick=createRoom; $('#ycPoolJoin').onclick=joinRoom; $('#ycPoolSolo').onclick=()=>startSolo(); $('#ycPoolStart').onclick=startGame; $('#ycPoolLeave').onclick=leaveRoom; $('#ycPoolGameLeave').onclick=leaveRoom;
  }
  async function load(){if(fs)return; const app=await import(APP); const fsm=await import(FIRESTORE); fs=fsm; db=fsm.getFirestore(app.getApp());}
  function open(){inject(); $('#yc-pool-root').classList.add('open'); $('#ycPoolLobby').style.display='grid'; $('#ycPoolGame').classList.remove('active'); solo=false;}
  function close(){if($('#yc-pool-root'))$('#yc-pool-root').classList.remove('open'); cleanup();}
  function setStatus(s){$('#ycPoolStatus').textContent=s}
  async function createRoom(){try{await load(); const {doc,setDoc,serverTimestamp}=fs; roomId=Math.random().toString(36).slice(2,8).toUpperCase(); const me=uid(); room={host:me,status:'waiting',players:[{uid:me,name:name()}],turn:0,state:null,updatedAt:serverTimestamp()}; await setDoc(doc(db,'poolRooms',roomId),room); watchRoom();}catch(e){$('#ycPoolError').textContent=e.message}}
  async function joinRoom(){const code=prompt('Enter the 6-character pool room code:'); if(!code)return; try{await load(); const {doc,getDoc,updateDoc,arrayUnion}=fs; roomId=code.trim().toUpperCase(); const ref=doc(db,'poolRooms',roomId), snap=await getDoc(ref); if(!snap.exists())throw Error('Room not found.'); const r=snap.data(); if(r.status!=='waiting')throw Error('That game has already started.'); if((r.players||[]).length>=4)throw Error('That room is full.'); await updateDoc(ref,{players:arrayUnion({uid:uid(),name:name()})}); watchRoom();}catch(e){$('#ycPoolError').textContent=e.message}}
  function watchRoom(){if(unsubRoom)unsubRoom(); const {doc,onSnapshot}=fs; unsubRoom=onSnapshot(doc(db,'poolRooms',roomId),snap=>{if(!snap.exists()){cleanup();setStatus('Room closed.');return} room=snap.data(); players=room.players||[]; renderLobby(); if(room.status==='playing'){showGame(); if(room.state)loadState(room.state);}});}
  function renderLobby(){const box=$('#ycPoolPlayers'); box.innerHTML=''; for(let i=0;i<4;i++){const p=players[i]; const d=document.createElement('div'); d.className='yc-pool-player'; d.innerHTML=p?`<span class="yc-pool-dot"></span><b>${esc(p.name)}</b>${p.uid===room.host?' · Host':''}`:`<span class="yc-pool-dot" style="opacity:.2"></span><span class="yc-pool-wait">WAITING FOR PLAYER</span>`; box.appendChild(d)} $('#ycPoolRoomTitle').textContent=room?.status==='waiting'?'Waiting room':'Pool match'; $('#ycPoolStatus').textContent=room?.status==='waiting'?(players.length<2?'WAITING FOR PLAYERS':'Waiting for host to start…'):'Game in progress'; const code=$('#ycPoolCode'); if(roomId){code.style.display='block';code.textContent='ROOM '+roomId} $('#ycPoolStart').style.display=room?.host===uid()&&room.status==='waiting'&&players.length>=1?'inline-block':'none'; $('#ycPoolLeave').style.display=roomId?'inline-block':'none';}
  async function startGame(){await load(); const {doc,updateDoc,serverTimestamp}=fs; const b=makeRack(); const state={balls:b,turn:0,turnUid:(players[0]||{}).uid||uid(),updatedAt:Date.now()}; await updateDoc(doc(db,'poolRooms',roomId),{status:'playing',state,updatedAt:serverTimestamp()});}
  function startSolo(){roomId=null;solo=true;room={status:'playing',host:uid(),players:[{uid:uid(),name:name()}]};players=room.players;showGame();loadState({balls:makeRack(),turn:0,turnUid:uid()});}
  function makeRack(){const a=[]; const cue={id:'cue',x:270,y:H/2,vx:0,vy:0,type:'cue'};a.push(cue); let n=0; const cx=780,cy=H/2; for(let row=0;row<5;row++)for(let j=0;j<=row;j++){const x=cx+row*(R*1.9),y=cy+(j-row/2)*R*2.02;a.push({id:'b'+n,x,y,vx:0,vy:0,type:n===7?'eight':'ball',num:n+1,color:palette[n++]})} return a}
  function showGame(){ $('#ycPoolLobby').style.display='none'; $('#ycPoolGame').classList.add('active'); canvas=$('#ycPoolCanvas');ctx=canvas.getContext('2d'); draw(); $('#ycPoolNames').innerHTML=players.map((p,i)=>`<span class="yc-pool-name ${i===Number(room?.turn||0)?'active':''}">${esc(p.name)}${i===Number(room?.turn||0)?' · turn':''}</span>`).join(''); $('#ycPoolTurn').innerHTML=`<strong>${esc(players[Number(room?.turn||0)]?.name||name())}</strong>'s shot`; canvas.onpointerdown=pointerDown;canvas.onpointermove=pointerMove;canvas.onpointerup=pointerUp; if(!raf){last=performance.now();raf=requestAnimationFrame(loop)}}
  function loadState(s){balls=(s.balls||makeRack()).map(b=>({...b})); draw();}
  function pointerDown(e){if(shotLock)return;const p=pos(e),c=balls.find(b=>b.type==='cue');if(!c||room?.turnUid!==uid()&&!solo)return;if(Math.hypot(p.x-c.x,p.y-c.y)<60){aiming=true;drag=p;}}
  function pointerMove(e){if(aiming)drag=pos(e)}
  async function pointerUp(e){if(!aiming)return; aiming=false; const c=balls.find(b=>b.type==='cue'),p=pos(e),dx=c.x-p.x,dy=c.y-p.y,len=Math.hypot(dx,dy)||1,s=Math.min(MAX_SPEED,len/20);c.vx=dx/len*s;c.vy=dy/len*s;shotLock=true;}
  function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
  function loop(t){const dt=Math.min(.035,(t-last)/1000);last=t;step(dt);draw();raf=requestAnimationFrame(loop)}
  function step(dt){let moving=false; for(const b of balls){if(b.pocketed)continue;b.x+=b.vx*60*dt;b.y+=b.vy*60*dt;b.vx*=Math.pow(FRICTION,dt*60);b.vy*=Math.pow(FRICTION,dt*60);if(Math.hypot(b.vx,b.vy)>.02)moving=true;for(const [px,py] of pockets)if(Math.hypot(b.x-px,b.y-py)<POCKET){b.pocketed=true;b.vx=b.vy=0} if(b.x<R+14){b.x=R+14;b.vx=Math.abs(b.vx)*CUSHION}if(b.x>W-R-14){b.x=W-R-14;b.vx=-Math.abs(b.vx)*CUSHION}if(b.y<R+14){b.y=R+14;b.vy=Math.abs(b.vy)*CUSHION}if(b.y>H-R-14){b.y=H-R-14;b.vy=-Math.abs(b.vy)*CUSHION}}
    for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){const a=balls[i],b=balls[j];if(a.pocketed||b.pocketed)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d&&d<R*2){const nx=dx/d,ny=dy/d,over=R*2-d;a.x-=nx*over/2;a.y-=ny*over/2;b.x+=nx*over/2;b.y+=ny*over/2;const rv=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rv<0){const imp=-(1+BALL_RESTITUTION)*rv/2;a.vx-=imp*nx;a.vy-=imp*ny;b.vx+=imp*nx;b.vy+=imp*ny}}}
    if(shotLock&&!moving){shotLock=false;if(!solo&&roomId&&room?.turnUid===uid())commitState()}}
  async function commitState(){try{const {doc,updateDoc,serverTimestamp}=fs;const idx=Math.max(0,(players.findIndex(p=>p.uid===uid())+1)%Math.max(1,players.length));const clean=balls.map(b=>({...b}));await updateDoc(doc(db,'poolRooms',roomId),{state:{balls:clean,turn:idx,turnUid:players[idx]?.uid||uid()},updatedAt:serverTimestamp()});}catch(e){console.warn(e)}}
  function draw(){if(!ctx)return;ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#0d6840');g.addColorStop(1,'#084a2f');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='#6b3f20';ctx.lineWidth=28;ctx.strokeRect(14,14,W-28,H-28);ctx.strokeStyle='#b98b50';ctx.lineWidth=2;ctx.strokeRect(28,28,W-56,H-56);for(const [x,y]of pockets){ctx.beginPath();ctx.arc(x,y,27,0,Math.PI*2);ctx.fillStyle='#050806';ctx.fill();ctx.strokeStyle='#1e3127';ctx.stroke()} for(let i=0;i<6;i++){const x=160+i*156;ctx.fillStyle='#d5b16a';ctx.beginPath();ctx.arc(x,17,4,0,7);ctx.fill()}for(const b of balls){if(b.pocketed)continue;ctx.beginPath();ctx.arc(b.x+2,b.y+3,R+1,0,7);ctx.fillStyle='#0005';ctx.fill();ctx.beginPath();ctx.arc(b.x,b.y,R,0,7);ctx.fillStyle=b.type==='cue'?'#f5f1e8':b.color;ctx.fill();if(b.type!=='cue'){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(b.x-3,b.y-4,2.4,0,7);ctx.fill();if(b.type==='eight'){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(b.x,b.y,5,0,7);ctx.fill();ctx.fillStyle='#111';ctx.font='bold 7px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('8',b.x,b.y)}}}if(aiming){const c=balls.find(b=>b.type==='cue'),dx=c.x-drag.x,dy=c.y-drag.y,l=Math.hypot(dx,dy)||1;ctx.strokeStyle='#ffffffaa';ctx.setLineDash([8,8]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(c.x+dx/l*260,c.y+dy/l*260);ctx.stroke();ctx.setLineDash([])}}
  async function leaveRoom(){try{if(roomId&&db){const {doc,updateDoc}=fs;if(room?.host===uid())await updateDoc(doc(db,'poolRooms',roomId),{status:'closed'});else await updateDoc(doc(db,'poolRooms',roomId),{players:(players||[]).filter(p=>p.uid!==uid())})}}catch(e){}cleanup();$('#ycPoolLobby').style.display='grid';$('#ycPoolGame').classList.remove('active');}
  function cleanup(){if(unsubRoom)unsubRoom();unsubRoom=null;roomId=null;room=null;players=[];shotLock=false;solo=false;}
  function hook(){inject();document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const t=(b.textContent||'').trim().toLowerCase();if(t==='pool'||t.startsWith('pool ')){e.preventDefault();e.stopImmediatePropagation();open()}},true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook);else hook();
})();
